export const enum DAY_TYPE {
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY,
}
export const DAY_TYPE_LIST = [
    { index: DAY_TYPE.MONDAY, value: 'Mon' },
    { index: DAY_TYPE.TUESDAY, value: 'Tue' },
    { index: DAY_TYPE.WEDNESDAY, value: 'Wed' },
    { index: DAY_TYPE.THURSDAY, value: 'Thu' },
    { index: DAY_TYPE.FRIDAY, value: 'Fri' },
    { index: DAY_TYPE.SATURDAY, value: 'Sat' },
    { index: DAY_TYPE.SUNDAY, value: 'Sun' },
]
export const enum MONTH_TYPE {
    January,
    February,
    March,
    April,
    May,
    June,
    July,
    August,
    September,
    October,
    November,
    December,
}
export const MONTH_TYPE_LIST = [
    { index: MONTH_TYPE.January, value: 'Jan' },
    { index: MONTH_TYPE.February, value: 'Feb' },
    { index: MONTH_TYPE.March, value: 'Mar' },
    { index: MONTH_TYPE.April, value: 'Ari' },
    { index: MONTH_TYPE.May, value: 'May' },
    { index: MONTH_TYPE.June, value: 'Jun' },
    { index: MONTH_TYPE.July, value: 'Jul' },
    { index: MONTH_TYPE.August, value: 'Aut' },
    { index: MONTH_TYPE.September, value: 'Sep' },
    { index: MONTH_TYPE.October, value: 'Oct' },
    { index: MONTH_TYPE.November, value: 'Nov' },
    { index: MONTH_TYPE.December, value: 'Dec' },
]

export const enum TIME_TYPE_LIST {
    SIX,
    SIX_QUARTER,
    SIX_HALF,
    SIX_FORTY_FIVE,
    SEVEN,
    SEVEN_QUARTER,
    SEVEN_HALF,
    SEVEN_FORTY_FIVE,
    EIGHT,
    EIGHT_QUARTER,
    EIGHT_HALF,
    EIGHT_FORTY_FIVE,
    NINE,
    NINE_QUARTER,
    NINE_HALF,
    NINE_FORTY_FIVE,
    TEN,
    TEN_QUARTER,
    TEN_HALF,
    TEN_FORTY_FIVE,
    ELEVEN,
    ELEVEN_QUARTER,
    ELEVEN_HALF,
    ELEVEN_FORTY_FIVE,
    TWELVE,
    TWELVE_QUARTER,
    TWELVE_HALF,
    TWELVE_FORTY_FIVE,
    THIRTEEN,
    THIRTEEN_QUARTER,
    THIRTEEN_HALF,
    THIRTEEN_FORTY_FIVE,
    FOURTEEN,
    FOURTEEN_QUARTER,
    FOURTEEN_HALF,
    FOURTEEN_FORTY_FIVE,
    FIFTEEN,
    FIFTEEN_QUARTER,
    FIFTEEN_HALF,
    FIFTEEN_FORTY_FIVE,
    SIXTEEN,
    SIXTEEN_QUARTER,
    SIXTEEN_HALF,
    SIXTEEN_FORTY_FIVE,
    SEVENTEEN,
    SEVENTEEN_QUARTER,
    SEVENTEEN_HALF,
    SEVENTEEN_FORTY_FIVE,
    EIGHTEEN,
    EIGHTEEN_QUARTER,
    EIGHTEEN_HALF,
    EIGHTEEN_FORTY_FIVE,
    NINETEEN,
    NINETEEN_QUARTER,
    NINETEEN_HALF,
    NINETEEN_FORTY_FIVE,
    TWENTY,
    TWENTY_QUARTER,
    TWENTY_HALF,
    TWENTY_FORTY_FIVE,
    TWENTY_ONE,
    TWENTY_ONE_QUARTER,
    TWENTY_ONE_HALF,
    TWENTY_ONE_FORTY_FIVE,
    TWENTY_TWO,
    TWENTY_TWO_QUARTER,
    TWENTY_TWO_HALF,
    TWENTY_TWO_FORTY_FIVE,
    TWENTY_THREE,
    TWENTY_THREE_QUARTER,
    TWENTY_THREE_HALF,
    TWENTY_THREE_FORTY_FIVE,
    TWENTY_FOUR,
    TWENTY_FOUR_QUARTER,
    TWENTY_FOUR_HALF,
    TWENTY_FOUR_FORTY_FIVE,
}
export const TIME_LIST = [
    { index: TIME_TYPE_LIST.SIX, value: '6 AM' },
    { index: TIME_TYPE_LIST.SEVEN, value: '7 AM' },
    { index: TIME_TYPE_LIST.EIGHT, value: '8 AM' },
    { index: TIME_TYPE_LIST.NINE, value: '9 AM' },
    { index: TIME_TYPE_LIST.TEN, value: '10 AM' },
    { index: TIME_TYPE_LIST.ELEVEN, value: '11 AM' },
    { index: TIME_TYPE_LIST.TWELVE, value: '12 AM' },
    { index: TIME_TYPE_LIST.THIRTEEN, value: '13 AM' },
    { index: TIME_TYPE_LIST.FOURTEEN, value: '14 AM' },
    { index: TIME_TYPE_LIST.FIFTEEN, value: '15 AM' },
    { index: TIME_TYPE_LIST.SIXTEEN, value: '16 AM' },
    { index: TIME_TYPE_LIST.SEVENTEEN, value: '17 AM' },
    { index: TIME_TYPE_LIST.EIGHTEEN, value: '18 AM' },
    { index: TIME_TYPE_LIST.NINETEEN, value: '19 AM' },
    { index: TIME_TYPE_LIST.TWENTY, value: '20 AM' },
    { index: TIME_TYPE_LIST.TWENTY_ONE, value: '21 AM' },
    { index: TIME_TYPE_LIST.TWENTY_TWO, value: '22 AM' },
    { index: TIME_TYPE_LIST.TWENTY_THREE, value: '23 AM' },
    { index: TIME_TYPE_LIST.TWENTY_FOUR, value: '24 AM' },
]
export const ALL_TIME_LIST = [
    { index: TIME_TYPE_LIST.SIX, value: 6 },
    { index: TIME_TYPE_LIST.SIX_QUARTER, value: '6:15' },
    { index: TIME_TYPE_LIST.SIX_HALF, value: '6:30' },
    { index: TIME_TYPE_LIST.SIXTEEN_FORTY_FIVE, value: '6:45' },
    { index: TIME_TYPE_LIST.SEVEN, value: '7' },
    { index: TIME_TYPE_LIST.SIX_QUARTER, value: '7:15' },
    { index: TIME_TYPE_LIST.SIX, value: '6' },
    { index: TIME_TYPE_LIST.SIX, value: '6' },
    { index: TIME_TYPE_LIST.SIX, value: '6 AM' },
    { index: TIME_TYPE_LIST.SIX, value: '6 AM' },
    { index: TIME_TYPE_LIST.SIX, value: '6 AM' },
    { index: TIME_TYPE_LIST.SIX, value: '6 AM' },
    { index: TIME_TYPE_LIST.SIX, value: '6 AM' },
    { index: TIME_TYPE_LIST.SIX, value: '6 AM' },
    { index: TIME_TYPE_LIST.SEVEN, value: '7 AM' },
    { index: TIME_TYPE_LIST.EIGHT, value: '8 AM' },
    { index: TIME_TYPE_LIST.NINE, value: '9 AM' },
    { index: TIME_TYPE_LIST.TEN, value: '10 AM' },
    { index: TIME_TYPE_LIST.ELEVEN, value: '11 AM' },
    { index: TIME_TYPE_LIST.TWELVE, value: '12 AM' },
    { index: TIME_TYPE_LIST.THIRTEEN, value: '13 AM' },
    { index: TIME_TYPE_LIST.FOURTEEN, value: '14 AM' },
    { index: TIME_TYPE_LIST.FIFTEEN, value: '15 AM' },
    { index: TIME_TYPE_LIST.SIXTEEN, value: '16 AM' },
    { index: TIME_TYPE_LIST.SEVENTEEN, value: '17 AM' },
    { index: TIME_TYPE_LIST.EIGHTEEN, value: '18 AM' },
    { index: TIME_TYPE_LIST.NINETEEN, value: '19 AM' },
    { index: TIME_TYPE_LIST.TWENTY, value: '20 AM' },
    { index: TIME_TYPE_LIST.TWENTY_ONE, value: '21 AM' },
    { index: TIME_TYPE_LIST.TWENTY_TWO, value: '22 AM' },
    { index: TIME_TYPE_LIST.TWENTY_THREE, value: '23 AM' },
    { index: TIME_TYPE_LIST.TWENTY_FOUR, value: '24 AM' },
]

export const CURRENT_TIME_LIST = [{ index: TIME_TYPE_LIST.SIX, value: '6 AM' }]

export const oneDay = 24 * 60 * 60 * 1000
